Test new bad chars + bibfile.

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -33,10 +33,10 @@ include:
     file: "latex/chktex.yml"
     ref: *ref
 
-  # https://git.dbogatov.org/templates/ci-snippets/-/blob/master/latex/cspell.yml
-  - project: "templates/ci-snippets"
-    file: "latex/cspell.yml"
-    ref: *ref
+  # # https://git.dbogatov.org/templates/ci-snippets/-/blob/master/latex/cspell.yml
+  # - project: "templates/ci-snippets"
+  #   file: "latex/cspell.yml"
+  #   ref: *ref
 
   # https://git.dbogatov.org/templates/ci-snippets/-/blob/master/latex-report/metrics.yml
   - project: "templates/ci-snippets"
@@ -87,6 +87,30 @@ include:
   - project: "templates/ci-snippets"
     file: "latex/pages.yml"
     ref: *ref
+
+cspell:
+  image: dbogatov/docker-images:cspell-latest
+  stage: lint
+  script:
+    - cspell -c .vscode/cSpell.json $LATEX_SRC/**/*.tex $LATEX_SRC/*.tex *.tex
+    - |
+      for character in " ̈" "„" "“" "–" "’"
+      do
+        echo ">>>> Checking $character "
+        ! grep -n $character $LATEX_SRC/**/*.tex $LATEX_SRC/*.tex $LATEX_SRC/*.bib
+
+        if [[ $? != 0 ]];
+        then
+          echo ">>> FAIL"
+          exit 1
+        fi
+      done
+  rules:
+    - if: "$DISABLE_REGULAR_PIPELINE"
+      when: never
+    - when: on_success
+  tags:
+    - docker
 
 
 # Uncomment to enable deletion of artifacts of previous jobs
